services:
  app:
    image: ghcr.io/rafee79/sanitization-app:latest
    container_name: sanitizer
    ports:
      - "8443:8443"
    volumes:
      - ./logs:/app/logs
      - ./outputs:/app/outputs
      - ./uploads:/app/uploads
      - ./temp:/app/temp
      - ./certs:/app/certs
    restart: unless-stopped
